
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "reemT@gmail.com",
    "username": "reem",
    "password": "password"
}

###


POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "123@gmail.com",
    "password": "12345678"
}

###


POST http://localhost:3000/chats/
Content-Type: application/json

{
    "recieverEmail": "reem@gmail.com"
}


###


POST http://localhost:3000/auth/logout

###

DELETE  http://localhost:3000/chats/1

###
GET http://localhost:3000/message/?chatId=3

###


POST http://localhost:3000/message/
Content-Type: application/json

{
    "chatId": "2",
    "content": "tarek"
}
###
GET http://localhost:3000/chats                                                                 